import assert from 'node:assert/strict';
function storage(){const m=new Map();return {getItem:k=>m.get(k)??null,setItem:(k,v)=>m.set(k,String(v)),removeItem:k=>m.delete(k)}}
globalThis.localStorage=storage();globalThis.sessionStorage=storage();
const {demoApi:api,demoLogin}=await import('../frontend/src/demo.ts');
demoLogin('admin@tallermeco.local');
assert.equal((await api('/orders')).length,3);
const order=await api('/orders','POST',{vehicleId:1,complaint:'Prueba automatizada',odometer:65000});
assert.equal((await api('/orders/'+order.id)).complaint,'Prueba automatizada');
await api('/orders/'+order.id+'/quote','PUT',{diagnosis:'Revisión',estimate:1000});
await api('/orders/'+order.id+'/status','POST',{status:'IN_PROGRESS',reason:'Autorizado (prueba)'});
await api('/orders/'+order.id+'/assignments','POST',{employeeId:1});
await api('/orders/'+order.id+'/works','POST',{employeeId:1,description:'Servicio',cost:100,price:300});
const old=(await api('/parts')).find(p=>p.id===1).stock;
await api('/inventory/movements','POST',{partId:1,orderId:order.id,kind:'CONSUMPTION',quantity:1,reason:'Test'});
assert.equal((await api('/parts')).find(p=>p.id===1).stock,old-1);
assert.equal((await api('/orders/'+order.id)).totals.total,520);
await assert.rejects(api('/inventory/movements','POST',{partId:1,orderId:order.id,kind:'CONSUMPTION',quantity:1000}),/Stock insuficiente/);
await api('/inventory/movements','POST',{partId:1,orderId:order.id,kind:'RETURN',quantity:1,reason:'Test'});
assert.equal((await api('/parts')).find(p=>p.id===1).stock,old);
await assert.rejects(api('/orders/'+order.id+'/status','POST',{status:'DELIVERED',reason:'Test'}),/Liquida el saldo/);
const work=(await api('/orders/'+order.id)).works[0];
await api(`/orders/${order.id}/works/${work.id}/status`,'PUT',{status:'DONE'});
await api('/orders/'+order.id+'/payments','POST',{kind:'PAYMENT',amount:300,method:'CASH',reason:'Test'});
assert.equal((await api('/orders/'+order.id)).totals.paid,300);
await api('/orders/'+order.id+'/status','POST',{status:'DELIVERED',reason:'Test'});
assert.equal((await api('/orders/'+order.id)).status,'DELIVERED');
assert.ok((await api('/reports?from=2020-01-01&to=2100-01-01')).revenue>=300);
demoLogin('cliente@tallermeco.local');
assert.ok((await api('/orders')).every(o=>o.customer_id===1));
await assert.rejects(api('/orders/1002'),/Orden no encontrada/);
demoLogin('mecanico@tallermeco.local');
assert.ok((await api('/orders')).every(o=>o.assignments.some(a=>a.employee_id===1)));
assert.ok(localStorage.getItem('tallermeco-prototype-v1'));
console.log('Prototipo verificado: altas, órdenes, trabajos, stock, devoluciones, cobros, reportes, persistencia y vistas por rol.');
