<script setup lang="ts">
import {ref,onMounted,watch,nextTick} from 'vue'
import ValidatedInput from '../../shared/ValidatedInput.vue'
import Modal from '../../../components/Modal.vue'
import {statusApi} from '../api/statusApi'
import {canDeleteStatus,type StatusKind,type EntityStatus} from '../types/status'
import {ApiError,notify} from '../../../api'
import {focusInvalid,type FieldErrors} from '../../shared/validation'
const kind=ref<StatusKind>('customers'),rows=ref<EntityStatus[]>([]),loading=ref(false),busy=ref(false),error=ref(''),formError=ref(''),show=ref(false),selected=ref<EntityStatus|null>(null),deleting=ref<EntityStatus|null>(null),errors=ref<FieldErrors>({}),form=ref({code:'',description:'',allowsOperations:false}),element=ref<HTMLElement|null>(null)
let generation=0
async function load(){const n=++generation;loading.value=true;error.value='';try{const data=await statusApi.list(kind.value);if(n===generation)rows.value=data}catch(e){if(n===generation)error.value=(e as Error).message}finally{if(n===generation)loading.value=false}}
function open(s:EntityStatus|null){selected.value=s;form.value={code:s?.code??'',description:s?.description??'',allowsOperations:s?.allowsOperations??false};errors.value={};formError.value='';show.value=true}
async function save(){if(busy.value)return;errors.value={};if(!/^[A-Z][A-Z0-9_]{1,39}$/.test(form.value.code.trim().toUpperCase()))errors.value.code='Usa 2–40 letras, números o guiones bajos; inicia con letra';if(!form.value.description.trim()||form.value.description.length>500||/[\u0000-\u001f\u007f]/.test(form.value.description))errors.value.description='Descripción obligatoria de hasta 500 caracteres, sin caracteres de control';if(kind.value==='customers'&&['DELETED','UPDATED','CANCELLED','INACTIVE'].includes(form.value.code.trim().toUpperCase()))errors.value.code='Ese código no corresponde a un estatus de cliente';if(kind.value==='vehicles'&&form.value.code.toUpperCase()==='IN_SERVICE')errors.value.code='En servicio se deriva de las órdenes';if(Object.keys(errors.value).length){await nextTick();focusInvalid(element.value,errors.value);return}busy.value=true;formError.value='';try{const data={...form.value,version:selected.value?.version};if(selected.value)await statusApi.update(kind.value,selected.value.id,data);else await statusApi.create(kind.value,data);show.value=false;await load();notify('Estatus guardado')}catch(e){formError.value=(e as Error).message;if(e instanceof ApiError)errors.value=e.fields}finally{busy.value=false}}
async function remove(){if(!deleting.value||busy.value)return;busy.value=true;formError.value='';try{await statusApi.delete(kind.value,deleting.value.id,deleting.value.version);deleting.value=null;await load();notify('Estatus eliminado')}catch(e){formError.value=(e as Error).message}finally{busy.value=false}}
watch(kind,()=>{show.value=false;deleting.value=null;void load()});onMounted(load)
</script>
<template><section class="page"><div class="page-heading"><div><h1>Catálogos de estatus</h1><p class="muted">Los estatus de clientes y vehículos se administran de forma independiente.</p></div><button class="btn primary" :disabled="busy||loading" @click="open(null)">Crear estatus</button></div><div class="tabs"><button :class="{active:kind==='customers'}" :disabled="busy" @click="kind='customers'">Clientes</button><button :class="{active:kind==='vehicles'}" :disabled="busy" @click="kind='vehicles'">Vehículos</button></div><p v-if="error" class="error" role="alert">{{error}} <button @click="load">Reintentar</button></p><section class="panel table-wrap" :aria-busy="loading"><p v-if="loading" role="status">Cargando estatus…</p><table v-else><thead><tr><th>Código</th><th>Descripción</th><th>Operaciones</th><th>Sistema</th><th>En uso</th><th>Acciones</th></tr></thead><tbody><tr v-for="s in rows" :key="s.id"><td>{{s.code}}</td><td>{{s.description}}</td><td>{{s.allowsOperations?'Permitidas':'Bloqueadas'}}</td><td>{{s.system?'Protegido':'Personalizado'}}</td><td>{{s.usageCount}}</td><td><button class="text-link" @click="open(s)">Editar</button> <button v-if="canDeleteStatus(s)" class="text-link" @click="deleting=s;formError=''">Eliminar</button><small v-else>{{s.system?'No eliminable':'Asignado a registros'}}</small></td></tr></tbody></table></section><Modal v-if="show" :title="selected?'Editar estatus':'Crear estatus'" :busy="busy" :error="formError" @close="show=false" @submit="save"><div ref="element"><ValidatedInput v-if="!selected?.system" v-model="form.code" name="code" label="Código" kind="statusCode" required :error="errors.code"/><label v-else>Código<input :value="form.code" readonly></label><ValidatedInput v-model="form.description" name="description" label="Descripción" kind="text" required :max="500" :error="errors.description"/><label><input v-model="form.allowsOperations" type="checkbox" :disabled="selected?.system"> Permite operaciones</label><p v-if="selected?.system" class="field-hint">Solo puedes cambiar la descripción de un estatus del sistema.</p></div></Modal><Modal v-if="deleting" title="Eliminar estatus personalizado" :busy="busy" :error="formError" @close="deleting=null" @submit="remove"><p>¿Eliminar {{deleting.code}}? No tiene registros asignados.</p></Modal></section></template>
