<script setup lang="ts">
import {ref,watch,nextTick} from 'vue'
import type {Vehicle,VehicleData} from '../types/vehicle'
import {vehicleFacade} from '../facade/vehicleFacade'
import {customerFacade} from '../../customers/facade/customerFacade'
import type {CustomerPage} from '../../customers/types/customer'
import ValidatedInput from '../../shared/ValidatedInput.vue'
import {validateVehicle,focusInvalid,type FieldErrors} from '../../shared/validation'
import {ApiError,notify} from '../../../api'
import {displayText} from '../../shared/presentation'
const props=defineProps<{workshopId:number;initial?:Vehicle;personal?:boolean}>(),emit=defineEmits<{saved:[];busy:[boolean];cancel:[]}>()
const busy=ref(false),error=ref(''),errors=ref<FieldErrors>({}),element=ref<HTMLFormElement|null>(null),customer=ref<number|''>(props.initial?.customerId??''),query=ref(''),page=ref(1),loading=ref(false),customers=ref<CustomerPage>({items:[],page:1,pageSize:10,totalItems:0,totalPages:0})
const form=ref<VehicleData>({vin:props.initial?.vin??'',plate:props.initial?.plate??'',make:props.initial?.make??'',model:props.initial?.model??'',trim:props.initial?.trim??'',color:props.initial?.color??'',year:props.initial?.year?.toString()??'',odometer:props.initial?.odometer?.toString()??''})
let generation=0
async function load(){if(props.initial||props.personal)return;const n=++generation;loading.value=true;try{const data=await customerFacade.list(props.workshopId,page.value,'ASC',query.value);if(n===generation)customers.value=data}catch(e){error.value=(e as Error).message}finally{if(n===generation)loading.value=false}}
watch([query,page],()=>{customer.value='';void load()});watch(query,()=>page.value=1);void load()
watch(()=>({...form.value}),(n,p)=>{for(const key of Object.keys(n) as (keyof VehicleData)[])if(n[key]!==p[key])delete errors.value[key]})
async function save(){if(busy.value)return;errors.value=validateVehicle(form.value);if(!props.initial&&!props.personal&&!customer.value)errors.value.customerId='Selecciona un cliente operativo del taller';if(Object.keys(errors.value).length){await nextTick();focusInvalid(element.value,errors.value);return}busy.value=true;emit('busy',true);error.value='';try{if(props.initial)await vehicleFacade.update(props.initial.id,props.workshopId,props.initial.version,form.value);else if(props.personal)await vehicleFacade.createPersonal(props.workshopId,form.value);else await vehicleFacade.create(Number(customer.value),props.workshopId,form.value);notify('Vehículo guardado');emit('saved')}catch(e){error.value=(e as Error).message;if(e instanceof ApiError){errors.value=e.fields;await nextTick();focusInvalid(element.value,errors.value)}}finally{busy.value=false;emit('busy',false)}}
</script>
<template><form ref="element" novalidate @submit.prevent="save"><fieldset :disabled="busy"><p v-if="initial" class="field-hint">Propietario: {{displayText(initial.customerName)}}. Los datos históricos faltantes deben completarse.</p><section v-if="!initial&&!personal"><label>Buscar cliente<input v-model="query" maxlength="160" :disabled="busy" placeholder="Nombre, teléfono o email"></label><label>Cliente propietario<select v-model="customer" name="customerId" required :disabled="loading" :aria-invalid="!!errors.customerId"><option value="" disabled>Selecciona un cliente operativo</option><option v-for="c in customers.items" :key="c.id" :value="c.id" :disabled="!c.allowsOperations">{{displayText(c.fullName)}}{{c.allowsOperations?'':' · Sin operaciones'}}</option></select><small v-if="errors.customerId" class="field-error">{{errors.customerId}}</small></label><div class="button-row"><button type="button" :disabled="loading||page===1" @click="page--">Anterior</button><span>Página {{page}} de {{customers.totalPages||1}}</span><button type="button" :disabled="loading||page>=customers.totalPages" @click="page++">Siguiente</button></div></section><div class="form-grid"><ValidatedInput v-model="form.vin" name="vin" label="VIN" kind="vin" required :error="errors.vin"/><ValidatedInput v-model="form.plate" name="plate" label="Placa" kind="plate" required :error="errors.plate"/><ValidatedInput v-model="form.make" name="make" label="Marca" kind="automotive" required :max="60" :error="errors.make"/><ValidatedInput v-model="form.model" name="model" label="Modelo" kind="automotive" required :max="80" :error="errors.model"/><ValidatedInput v-model="form.trim" name="trim" label="Versión" kind="automotive" required :max="80" :error="errors.trim"/><ValidatedInput v-model="form.color" name="color" label="Color" kind="automotive" required :max="60" :error="errors.color"/><ValidatedInput v-model="form.year" name="year" label="Año" kind="year" required :error="errors.year"/><ValidatedInput v-model="form.odometer" name="odometer" label="Kilometraje (km)" kind="odometer" :error="errors.odometer"/></div></fieldset><p v-if="error" class="error" role="alert">{{error}}</p><footer class="form-actions"><button type="button" class="btn secondary" :disabled="busy" @click="emit('cancel')">Cancelar</button><button class="btn primary" :disabled="busy">{{busy?'Guardando…':'Guardar vehículo'}}</button></footer></form></template>
