// Local prototype only. No production authentication or connection to MariaDB.
import type {Row} from './api'
const today=new Date().toISOString()
const initial={
 customers:[{id:1,full_name:'Ana Martínez',phone:'55 2480 3192',email:'ana@ejemplo.local'},{id:2,full_name:'Carlos Mendoza',phone:'55 9812 4040',email:'carlos@ejemplo.local'},{id:3,full_name:'Sofía Ramírez',phone:'55 7321 0890',email:'sofia@ejemplo.local'}],
 employees:[{id:1,user_id:2,full_name:'Miguel Torres',email:'mecanico@tallermeco.local',role_code:'MECHANIC',active:true,enabled:true},{id:2,user_id:3,full_name:'Diego López',email:'diego@ejemplo.local',role_code:'MECHANIC',active:true,enabled:true}],
 vehicles:[{id:1,customer_id:1,customer_name:'Ana Martínez',make:'Volkswagen',model:'Golf',model_year:2020,license_plate:'NZA-482-B',vin:''},{id:2,customer_id:2,customer_name:'Carlos Mendoza',make:'Toyota',model:'Corolla',model_year:2022,license_plate:'PBC-219-A',vin:''},{id:3,customer_id:3,customer_name:'Sofía Ramírez',make:'Mazda',model:'CX-5',model_year:2021,license_plate:'MXJ-730-C',vin:''}],
 parts:[{id:1,sku:'ACE-5W30',name:'Aceite sintético 5W-30',unit:'L',stock:18,minimum_stock:8,reference_cost:145,reference_price:220},{id:2,sku:'FIL-AC01',name:'Filtro de aceite',unit:'UNIT',stock:3,minimum_stock:5,reference_cost:80,reference_price:150},{id:3,sku:'BAL-DEL',name:'Juego de balatas delanteras',unit:'UNIT',stock:2,minimum_stock:3,reference_cost:650,reference_price:980},{id:4,sku:'REF-01',name:'Anticongelante 50/50',unit:'L',stock:12,minimum_stock:4,reference_cost:70,reference_price:120}],
 orders:[{id:1003,vehicle_id:1,customer_id:1,status:'IN_PROGRESS',complaint:'Servicio de los 60,000 km y revisión de frenos.',diagnosis:'Cambio de aceite, filtro y revisión general.',estimated_amount:1800,received_at:today,version:0,assignments:[{employee_id:1,full_name:'Miguel Torres'}],works:[{id:1,employee_id:1,mechanic:'Miguel Torres',description:'Servicio preventivo de 60,000 km',status:'IN_PROGRESS',sale_price:550,direct_cost:250}],parts:[{id:1,part_id:1,name:'Aceite sintético 5W-30',kind:'CONSUMPTION',quantity:-4,unit_price:220,unit_cost:145}],payments:[{id:1,kind:'PAYMENT',amount:500,method:'CASH',reason:'Anticipo',created_at:today}],history:[{new_status:'RECEIVED',reason:'Recepción del vehículo',created_at:today},{new_status:'IN_PROGRESS',reason:'Presupuesto autorizado por el cliente',created_at:today}]},{id:1002,vehicle_id:2,customer_id:2,status:'READY',complaint:'Ruido en los frenos delanteros.',diagnosis:'Sustitución de balatas delanteras.',estimated_amount:1600,received_at:today,version:0,assignments:[{employee_id:2,full_name:'Diego López'}],works:[{id:2,employee_id:2,mechanic:'Diego López',description:'Sustitución y ajuste de balatas',status:'DONE',sale_price:450,direct_cost:200}],parts:[{id:2,part_id:3,name:'Juego de balatas delanteras',kind:'CONSUMPTION',quantity:-1,unit_price:980,unit_cost:650}],payments:[],history:[{new_status:'READY',reason:'Pruebas de frenado satisfactorias',created_at:today}]},{id:1001,vehicle_id:3,customer_id:3,status:'DIAGNOSIS',complaint:'Testigo de motor encendido.',diagnosis:'',estimated_amount:0,received_at:today,version:0,assignments:[{employee_id:1,full_name:'Miguel Torres'}],works:[],parts:[],payments:[],history:[{new_status:'DIAGNOSIS',reason:'Escaneo inicial',created_at:today}]}],audit:[],movements:[]
}
const key='tallermeco-prototype-v1'
let state:Row;try{state=JSON.parse(localStorage.getItem(key)||'null')||structuredClone(initial)}catch{state=structuredClone(initial)}
export let demoUser:Row|null=JSON.parse(sessionStorage.getItem('taller-demo-user')||'null')
export function demoLogin(email:string){const role=email.startsWith('mecanico')?'MECHANIC':email.startsWith('cliente')?'CLIENT':'ADMIN';demoUser={id:role==='ADMIN'?1:role==='MECHANIC'?2:4,email,name:role==='ADMIN'?'Alex Rivera':role==='MECHANIC'?'Miguel Torres':'Ana Martínez',role,phone:''};sessionStorage.setItem('taller-demo-user',JSON.stringify(demoUser))}
function save(action:string){state.audit.unshift({id:Date.now(),action,entity_type:'prototipo',created_at:new Date().toISOString(),actor:demoUser?.email});localStorage.setItem(key,JSON.stringify(state))}
function id(rows:Row[]){return Math.max(0,...rows.map(r=>r.id))+1}
function decorate(o:Row){const vehicle=state.vehicles.find((v:Row)=>v.id===o.vehicle_id)||{};const customer=state.customers.find((c:Row)=>c.id===o.customer_id)||{};const total=o.works.filter((w:Row)=>w.status!=='CANCELLED').reduce((s:number,w:Row)=>s+Number(w.sale_price),0)+o.parts.reduce((s:number,p:Row)=>s-Number(p.quantity)*Number(p.unit_price),0);const paid=o.payments.reduce((s:number,p:Row)=>s+Number(p.amount)*(p.kind==='REFUND'?-1:1),0);const direct_cost=o.works.reduce((s:number,w:Row)=>s+Number(w.direct_cost||0),0)+o.parts.reduce((s:number,p:Row)=>s-Number(p.quantity)*Number(p.unit_cost||0),0);return {...o,...{make:vehicle.make,model:vehicle.model,license_plate:vehicle.license_plate,customer_name:customer.full_name},vehicle,customer,totals:{total,paid,direct_cost}}}
function visible(){return state.orders.filter((o:Row)=>demoUser?.role==='CLIENT'?o.customer_id===1:demoUser?.role==='MECHANIC'?o.assignments.some((a:Row)=>a.employee_id===1):true)}
export async function demoApi(path:string,method='GET',body:any={}):Promise<any>{
 const [url,query]=path.split('?');const bits=url.split('/').filter(Boolean);const resource=bits[0];const recordId=Number(bits[1]);
 if(url==='/auth/me'){if(!demoUser)throw new Error('Inicia sesión');return structuredClone(demoUser)}
 if(url==='/auth/logout'){demoUser=null;sessionStorage.removeItem('taller-demo-user');return}
 if(url==='/auth/forgot')return {message:'Vista de demostración: no se envían correos. Puedes entrar con los accesos de prueba.'}
 if(url==='/auth/register'||url==='/auth/reset'||url==='/account/password')throw new Error('Esta función requiere conectar el backend. Usa los accesos de demostración.')
 if(url==='/account'){Object.assign(demoUser!,body);sessionStorage.setItem('taller-demo-user',JSON.stringify(demoUser));return}
 if(!demoUser)throw new Error('Inicia sesión')
 if(url==='/dashboard'){const orders=visible().map(decorate);return {active:orders.filter((o:Row)=>!['CANCELLED','DELIVERED'].includes(o.status)).length,ready:orders.filter((o:Row)=>o.status==='READY').length,completed:orders.filter((o:Row)=>o.status==='DELIVERED').length,orders,lowStock:state.parts.filter((p:Row)=>p.stock<=p.minimum_stock),todayPayments:state.orders.flatMap((o:Row)=>o.payments).reduce((n:number,p:Row)=>n+Number(p.amount)*(p.kind==='REFUND'?-1:1),0)}}
 if(url==='/reports'){const q=new URLSearchParams(query),from=q.get('from')||'',to=q.get('to')||'';const inRange=(v:string)=>!from||v.slice(0,10)>=from&&v.slice(0,10)<=to;const orders=state.orders.filter((o:Row)=>o.status==='DELIVERED'&&inRange(o.closed_at||today)).map((o:Row)=>({...decorate(o),...decorate(o).totals}));const revenue=orders.reduce((s:number,o:Row)=>s+o.total,0),cost=orders.reduce((s:number,o:Row)=>s+o.direct_cost,0);return {orders,revenue,cost,margin:revenue-cost,payments:state.orders.flatMap((o:Row)=>o.payments).filter((p:Row)=>inRange(p.created_at)).reduce((s:number,p:Row)=>s+Number(p.amount)*(p.kind==='REFUND'?-1:1),0),workload:state.employees.map((e:Row)=>({...e,active_orders:state.orders.filter((o:Row)=>!['DELIVERED','CANCELLED'].includes(o.status)&&o.assignments.some((a:Row)=>a.employee_id===e.id)).length})),works:[]}}
 if(resource==='orders'){
  if(method==='GET')return recordId?structuredClone(decorate(visible().find((o:Row)=>o.id===recordId)||(()=>{throw new Error('Orden no encontrada')})())):structuredClone(visible().map(decorate))
  if(!recordId){const v=state.vehicles.find((v:Row)=>v.id===Number(body.vehicleId));if(!v)throw new Error('Selecciona un vehículo');const o={id:id(state.orders),vehicle_id:v.id,customer_id:v.customer_id,complaint:body.complaint,odometer_km:body.odometer,status:'RECEIVED',received_at:today,version:0,estimated_amount:0,assignments:[],works:[],parts:[],payments:[],history:[{new_status:'RECEIVED',reason:'Recepción',created_at:today}]};state.orders.unshift(o);save('ORDER_CREATED');return{id:o.id}}
  const o=state.orders.find((o:Row)=>o.id===recordId);if(!o)throw new Error('Orden no encontrada');const action=bits[2]
  if(['DELIVERED','CANCELLED'].includes(o.status)&&action!=='status')throw new Error('La orden está cerrada')
  if(action==='quote')Object.assign(o,{diagnosis:body.diagnosis,estimated_amount:Number(body.estimate)})
  if(action==='assignments'){const e=state.employees.find((e:Row)=>e.id===Number(body.employeeId));if(o.assignments.some((a:Row)=>a.employee_id===e.id))throw new Error('Ya está asignado');o.assignments.push({employee_id:e.id,full_name:e.full_name})}
  if(action==='status'){const t=decorate(o).totals;if(body.status==='READY'&&(!o.works.length||o.works.some((w:Row)=>w.status==='IN_PROGRESS')))throw new Error('Termina los trabajos antes de marcar como listo');if(body.status==='DELIVERED'&&t.total!==t.paid)throw new Error('Liquida el saldo antes de entregar');if(body.status==='CANCELLED'&&(t.paid>0||o.parts.reduce((s:number,p:Row)=>s+p.quantity,0)!==0))throw new Error('Reembolsa cobros y devuelve piezas antes de cancelar');o.status=body.status;o.closed_at=body.status==='DELIVERED'?new Date().toISOString():null;o.history.push({new_status:body.status,reason:body.reason,created_at:new Date().toISOString()})}
  if(action==='works'){if(bits[3]){const w=o.works.find((w:Row)=>w.id===Number(bits[3]));if(bits[4]==='price')Object.assign(w,{sale_price:Number(body.price),direct_cost:Number(body.cost)});else w.status=body.status}else{if(o.status!=='IN_PROGRESS')throw new Error('Autoriza la orden e inicia la reparación primero');const e=state.employees.find((e:Row)=>e.id===Number(body.employeeId));if(!e)throw new Error('Selecciona un mecánico');o.works.push({id:Date.now(),employee_id:e.id,mechanic:e.full_name,description:body.description,status:'IN_PROGRESS',sale_price:Number(body.price),direct_cost:Number(body.cost)})}}
  if(action==='payments'){const total=decorate(o).totals;if(Number(body.amount)<=0)throw new Error('Monto inválido');if(body.kind==='REFUND'&&Number(body.amount)>total.paid)throw new Error('El reembolso supera lo cobrado');if(body.kind==='PAYMENT'&&total.paid+Number(body.amount)>Math.max(total.total,o.estimated_amount))throw new Error('El cobro supera el presupuesto');o.payments.push({id:Date.now(),...body,amount:Number(body.amount),created_at:new Date().toISOString()})}
  o.version++;save(action.toUpperCase());return
 }
 if(resource==='inventory'&&bits[1]==='movements'){
  if(method==='GET')return structuredClone(state.movements)
  const p=state.parts.find((p:Row)=>p.id===Number(body.partId));if(!p)throw new Error('Selecciona una pieza');const qty=Number(body.quantity);if(!Number.isFinite(qty)||qty===0)throw new Error('Cantidad inválida');if(body.kind!=='ADJUSTMENT'&&qty<=0)throw new Error('Introduce una cantidad positiva');let signed=body.kind==='CONSUMPTION'?-Math.abs(qty):qty;
  const order=state.orders.find((o:Row)=>o.id===Number(body.orderId));if(['CONSUMPTION','RETURN'].includes(body.kind)&&!order)throw new Error('Selecciona una orden');if(order&&['CANCELLED','DELIVERED'].includes(order.status))throw new Error('Orden cerrada');if(body.kind==='CONSUMPTION'&&order.status!=='IN_PROGRESS')throw new Error('La orden debe estar en reparación');if(body.kind==='RETURN'){const net=-order.parts.filter((m:Row)=>m.part_id===p.id).reduce((s:number,m:Row)=>s+m.quantity,0);if(qty>net)throw new Error('Devolución mayor al consumo')}
  if(p.stock+signed<0)throw new Error('Stock insuficiente');p.stock+=signed;const movement={id:Date.now(),...body,part_id:p.id,quantity:signed,name:p.name,sku:p.sku,unit_cost:Number(body.cost||p.reference_cost),unit_price:p.reference_price,created_at:new Date().toISOString()};if(order)order.parts.push(movement);state.movements.unshift(movement);save('INVENTORY_MOVEMENT');return
 }
 const table=resource==='inventory'?'parts':resource
 if(['customers','vehicles','employees','parts','audit'].includes(table)){
  if(method==='GET'){const rows=state[table];return structuredClone(table==='vehicles'&&demoUser.role==='CLIENT'?rows.filter((v:Row)=>v.customer_id===1):rows)}
  if(bits[2]==='access'){const e=state.employees.find((e:Row)=>e.user_id===recordId);e.enabled=body.enabled;save('ACCESS_CHANGED');return}
  let values={...body};if(table==='customers')values={full_name:body.name,phone:body.phone};if(table==='vehicles'){const customerId=demoUser.role==='CLIENT'?1:Number(body.customerId);values={customer_id:customerId,customer_name:state.customers.find((c:Row)=>c.id===customerId)?.full_name,make:body.make,model:body.model,model_year:body.year,license_plate:body.plate,vin:body.vin}}
  if(table==='parts')values={sku:body.sku,name:body.name,unit:body.unit,minimum_stock:Number(body.minimum),reference_price:Number(body.price)}
  if(table==='employees')values={full_name:body.name,email:body.email,role_code:body.role,user_id:Date.now(),enabled:true,active:true}
  if(recordId)Object.assign(state[table].find((r:Row)=>r.id===recordId),values);else state[table].push({id:id(state[table]),stock:0,reference_cost:0,...values});save(table.toUpperCase()+'_SAVED');return
 }
 throw new Error('Función no disponible en este prototipo')
}
export function resetDemo(){localStorage.removeItem(key);location.reload()}
