package mx.tallermeco.vehicle;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.support.GeneratedKeyHolder;
import org.springframework.stereotype.Repository;
import java.sql.Statement;
import java.util.*;
@Repository
public class VehicleRepository {
 public record Vehicle(long id,long customerId,String customerName,String vin,String plate,String make,String model,String trim,Integer year,String color,Integer odometer,long statusId,String statusCode,String statusDescription,boolean allowsOperations,long version,boolean inService){}
 public record Page(List<Vehicle> items,int page,int pageSize,long totalItems,long totalPages){}
 private final JdbcTemplate jdbc;public VehicleRepository(JdbcTemplate jdbc){this.jdbc=jdbc;}
 private static final String FROM=" FROM vehicle v JOIN customer c ON c.id=v.customer_id JOIN vehicle_status s ON s.id=v.status_id JOIN customer_workshop cw ON cw.customer_id=c.id WHERE cw.workshop_id=? AND cw.active=true";
 private static final String SELECT="SELECT v.*,c.full_name customer_name,s.code status_code,s.description status_description,s.allows_operations,EXISTS(SELECT 1 FROM service_order o WHERE o.vehicle_id=v.id AND o.status IN ('RECEIVED','DIAGNOSIS','AWAITING_APPROVAL','IN_PROGRESS','READY')) in_service";
 private Vehicle map(java.sql.ResultSet r,int n)throws java.sql.SQLException{return new Vehicle(r.getLong("id"),r.getLong("customer_id"),r.getString("customer_name"),r.getString("vin"),r.getString("license_plate"),r.getString("make"),r.getString("model"),r.getString("trim_level"),(Integer)r.getObject("model_year",Integer.class),r.getString("color"),(Integer)r.getObject("odometer_km",Integer.class),r.getLong("status_id"),r.getString("status_code"),r.getString("status_description"),r.getBoolean("allows_operations"),r.getLong("version"),r.getBoolean("in_service"));}
 public Optional<Vehicle> get(long id,long workshop,boolean lock){return jdbc.query(SELECT+FROM+" AND v.id=?"+(lock?" FOR UPDATE":""),this::map,workshop,id).stream().findFirst();}
 public Page page(long workshop,int page,int size,String sort,String direction,String query,Long status){String column=switch(sort){case "make"->"v.make";case "vin"->"v.vin";case "plate"->"v.license_plate";case "id"->"v.id";default->throw new IllegalArgumentException("Orden inválido");};String order=direction.equals("DESC")?"DESC":"ASC";String filter=FROM+" AND (?='' OR LOCATE(?,COALESCE(v.vin,''))>0 OR LOCATE(?,COALESCE(v.license_plate,''))>0 OR LOCATE(?,v.make)>0 OR LOCATE(?,v.model)>0)";var args=new ArrayList<Object>(List.of(workshop,query,query,query,query,query));if(status!=null){filter+=" AND v.status_id=?";args.add(status);}long count=Objects.requireNonNull(jdbc.queryForObject("SELECT COUNT(*)"+filter,Long.class,args.toArray()));args.add(size);args.add(((long)page-1)*size);var items=jdbc.query(SELECT+filter+" ORDER BY "+column+" "+order+",v.id "+order+" LIMIT ? OFFSET ?",this::map,args.toArray());return new Page(items,page,size,count,(count+size-1)/size);}
 public List<Map<String,Object>> personalWorkshops(long customer){return jdbc.queryForList("SELECT w.id,w.name FROM customer_workshop cw JOIN workshop w ON w.id=cw.workshop_id JOIN company co ON co.id=w.company_id WHERE cw.customer_id=? AND cw.active=true AND w.active=true AND co.active=true ORDER BY w.name,w.id",customer);}
 public boolean personalWorkshop(long customer,long workshop){return !jdbc.queryForList("SELECT w.id FROM customer_workshop cw JOIN workshop w ON w.id=cw.workshop_id JOIN company co ON co.id=w.company_id WHERE cw.customer_id=? AND cw.workshop_id=? AND cw.active=true AND w.active=true AND co.active=true FOR UPDATE",customer,workshop).isEmpty();}
 public List<Map<String,Object>> personal(long customer){return jdbc.queryForList("SELECT v.*,s.code status_code,s.allows_operations,c.full_name customer_name FROM vehicle v JOIN customer c ON c.id=v.customer_id JOIN vehicle_status s ON s.id=v.status_id WHERE v.customer_id=? ORDER BY v.id DESC LIMIT 500",customer);}
 public List<Map<String,Object>> assigned(long employee){return jdbc.queryForList("SELECT v.*,s.code status_code,s.allows_operations,c.full_name customer_name FROM vehicle v JOIN customer c ON c.id=v.customer_id JOIN vehicle_status s ON s.id=v.status_id WHERE EXISTS(SELECT 1 FROM service_order o JOIN order_assignment a ON a.order_id=o.id WHERE o.vehicle_id=v.id AND a.employee_id=?) ORDER BY v.id DESC LIMIT 500",employee);}
 public long create(long customer,VehicleData r){var keys=new GeneratedKeyHolder();jdbc.update(c->{var p=c.prepareStatement("INSERT INTO vehicle(customer_id,vin,license_plate,make,model,trim_level,model_year,color,odometer_km) VALUES (?,?,?,?,?,?,?,?,?)",Statement.RETURN_GENERATED_KEYS);Object[] values={customer,r.vin(),r.plate(),r.make(),r.model(),r.trim(),Integer.valueOf(r.year()),r.color(),r.odometer()==null?null:Integer.valueOf(r.odometer())};for(int i=0;i<values.length;i++)p.setObject(i+1,values[i]);return p;},keys);return Objects.requireNonNull(keys.getKey()).longValue();}
 public void update(long id,VehicleData r){jdbc.update("UPDATE vehicle SET vin=?,license_plate=?,make=?,model=?,trim_level=?,model_year=?,color=?,odometer_km=?,version=version+1 WHERE id=?",r.vin(),r.plate(),r.make(),r.model(),r.trim(),Integer.valueOf(r.year()),r.color(),r.odometer()==null?null:Integer.valueOf(r.odometer()),id);}
 public void status(long id,long status){jdbc.update("UPDATE vehicle SET status_id=?,version=version+1 WHERE id=?",status,id);}
}
