<script setup lang="ts">
import {ref,onMounted} from 'vue'
import type {Workshop,Company} from '../types/workshop'
import {workshopFacade} from '../facade/workshopFacade'
import WorkshopForm from '../components/WorkshopForm.vue'
import WorkshopAccessForm from '../components/WorkshopAccessForm.vue'
const workshops=ref<Workshop[]>([]),companies=ref<Company[]>([]),selected=ref<Workshop|undefined>(),creating=ref(false),editing=ref(false),loading=ref(false),busy=ref(false),error=ref('')
async function load(){loading.value=true;error.value='';try{[workshops.value,companies.value]=await Promise.all([workshopFacade.list(),workshopFacade.companies()])}catch(e){error.value=(e as Error).message}finally{loading.value=false}}
async function open(w:Workshop){error.value='';try{selected.value=await workshopFacade.get(w.id);creating.value=false;editing.value=false}catch(e){error.value=(e as Error).message}}
async function saved(w:Workshop){creating.value=false;editing.value=false;await load();await open(w)}
onMounted(load)
</script>
<template><section class="page"><div class="page-heading"><div><p class="eyebrow">ADMINISTRACIÓN</p><h1>Talleres</h1><p class="muted">Información, banners y acceso de recepción.</p></div><button class="btn primary" :disabled="busy" @click="creating=true;selected=undefined;editing=false">Registrar taller</button></div><p v-if="error" class="error" role="alert">{{error}} <button class="text-link" @click="load">Reintentar</button></p><div v-if="loading" class="loading panel" role="status">Cargando talleres…</div><section v-else class="panel directory-panel"><div class="table-wrap"><table v-if="workshops.length"><thead><tr><th>Taller</th><th>Razón social / RFC</th><th>Estado</th><th>Administrar</th></tr></thead><tbody><tr v-for="w in workshops" :key="w.id"><td>{{w.name}}</td><td>{{w.legalName||'Completar ficha'}}<small>{{w.rfc||'RFC no registrado'}}</small></td><td>{{w.active?'Activo':'Inactivo'}}</td><td><button class="btn secondary small-btn" :disabled="busy" @click="open(w)">Ver taller</button></td></tr></tbody></table><p v-else class="empty">Registra el primer taller para empezar.</p></div></section>
 <WorkshopForm v-if="creating" :companies="companies" @busy="busy=$event" @saved="saved" @cancel="creating=false" />
 <section v-if="selected" :key="selected.id" class="customer-detail"><div v-if="selected.bannerReference" class="workshop-banner hero"><img :src="workshopFacade.bannerUrl(selected)" :alt="selected.name"></div><header class="customer-detail-header"><div><p class="eyebrow">TALLER #{{selected.id}}</p><h2>{{selected.name}}</h2></div><div class="button-row"><button class="btn secondary" :disabled="busy" @click="editing=!editing">{{editing?'Cancelar edición':'Editar taller'}}</button><button class="btn secondary" :disabled="busy" @click="selected=undefined">Cerrar ficha</button></div></header><WorkshopForm v-if="editing" :initial="selected" :companies="companies" @busy="busy=$event" @saved="saved" @cancel="editing=false" /><div v-else class="customer-info-grid"><section class="info-section"><h3>Información del taller</h3><dl><div><dt>Razón social</dt><dd>{{selected.legalName||'No registrada'}}</dd></div><div><dt>RFC</dt><dd>{{selected.rfc||'No registrado'}}</dd></div><div><dt>Email</dt><dd>{{selected.email||'No registrado'}}</dd></div><div><dt>Teléfono</dt><dd>{{selected.phone||'No registrado'}}</dd></div><div><dt>Dirección</dt><dd>{{selected.street}}, {{selected.neighborhood}}<br>{{selected.municipality}}, {{selected.state}} · CP {{selected.postalCode}}</dd></div></dl></section><WorkshopAccessForm :id="selected.id" /></div></section>
</section></template>
