<script setup lang="ts">
import {ref,computed,onMounted} from 'vue';import {useRoute,useRouter} from 'vue-router';import {api,session,statuses,date,money,notify,type Row} from '../api';import Icon from '../components/Icon.vue';import Badge from '../components/Badge.vue';import Modal from '../components/Modal.vue'
const route=useRoute(),router=useRouter(),rows=ref<Row[]>([]),vehicles=ref<Row[]>([]),query=ref(''),filter=ref(''),show=ref(false),busy=ref(false),error=ref(''),pageError=ref('');const form=ref({vehicleId:'',complaint:'',odometer:0});const filtered=computed(()=>rows.value.filter(r=>(!filter.value||r.status===filter.value)&&JSON.stringify(r).toLowerCase().includes(query.value.toLowerCase())))
async function load(){try{rows.value=await api('/orders')}catch(e:any){pageError.value=e.message}}
async function open(){vehicles.value=await api('/vehicles');show.value=true;error.value=''}
async function save(){busy.value=true;error.value='';try{const r=await api('/orders','POST',{...form.value,vehicleId:Number(form.value.vehicleId)});show.value=false;notify('Orden creada');router.push('/orders/'+r.id)}catch(e:any){error.value=e.message}finally{busy.value=false}}
onMounted(async()=>{await load();if(route.query.new&&session.user?.role==='ADMIN')await open()})
</script>
<template><div class="page-heading"><div><p class="eyebrow">DEL INGRESO A LA ENTREGA</p><h1>Órdenes de servicio</h1><p class="muted">Cada vehículo tiene una historia. Aquí puedes seguirla.</p></div><button v-if="session.user?.role==='ADMIN'" class="btn primary" @click="open"><Icon name="plus"/>Nueva orden</button></div><div class="tabs"><button :class="{active:!filter}" @click="filter=''">Todas las órdenes <span>{{rows.length}}</span></button><button :class="{active:filter==='IN_PROGRESS'}" @click="filter='IN_PROGRESS'">En reparación</button><button :class="{active:filter==='READY'}" @click="filter='READY'">Listas para entrega</button><button :class="{active:filter==='DELIVERED'}" @click="filter='DELIVERED'">Entregadas</button></div><section class="panel"><div class="table-toolbar"><div class="search"><Icon name="search"/><input v-model="query" placeholder="Buscar vehículo, cliente u orden…" aria-label="Buscar órdenes"></div><select v-model="filter" aria-label="Estado"><option value="">Todos los estados</option><option v-for="(label,key) in statuses" v-show="!['DONE','PENDING'].includes(key)" :value="key">{{label}}</option></select></div><p v-if="pageError" class="error">{{pageError}}</p><div class="table-wrap"><table><thead><tr><th>Orden</th><th>Vehículo</th><th>Cliente</th><th>Ingreso</th><th>Presupuesto</th><th>Estado</th><th></th></tr></thead><tbody><tr v-for="r in filtered" :key="r.id"><td><RouterLink class="order-number" :to="'/orders/'+r.id">#{{String(r.id).padStart(4,'0')}}</RouterLink></td><td><strong>{{r.make}} {{r.model}}</strong><small>{{r.license_plate||'Sin matrícula'}}</small></td><td>{{r.customer_name}}</td><td>{{date(r.received_at)}}</td><td>{{money(r.estimated_amount)}}</td><td><Badge :status="r.status"/></td><td><RouterLink class="icon-button" :to="'/orders/'+r.id" :aria-label="'Abrir orden '+r.id"><Icon name="arrow"/></RouterLink></td></tr></tbody></table><div v-if="!filtered.length" class="empty"><Icon name="orders" :size="38"/><h3>No hay órdenes con estos filtros</h3><p>Prueba otra búsqueda o crea una nueva orden.</p></div></div><div class="table-footer">{{filtered.length}} órdenes · Mostrando hasta 500 registros</div></section><Modal v-if="show" title="Recibir un vehículo" :busy="busy" :error="error" @close="show=false" @submit="save"><label>Vehículo<select v-model="form.vehicleId" required><option value="" disabled>Selecciona un vehículo</option><option v-for="v in vehicles" :value="v.id">{{v.make}} {{v.model}} · {{v.license_plate}} · {{v.customer_name}}</option></select></label><p v-if="!vehicles.length" class="muted">Primero registra un vehículo en la sección Vehículos.</p><label>¿Qué necesita el vehículo?<textarea v-model="form.complaint" required maxlength="3000" placeholder="Describe el motivo de la visita…"></textarea></label><label>Kilometraje<input v-model.number="form.odometer" type="number" min="0" required></label></Modal></template>
