<script setup lang="ts">
import {ref,onMounted} from 'vue';import {api,money,type Row} from '../api';import Icon from '../components/Icon.vue'
const day=(d:Date)=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;const to=ref(day(new Date())),from=ref(day(new Date(new Date().getFullYear(),new Date().getMonth(),1))),data=ref<Row|null>(null),error=ref('')
async function load(){error.value='';try{data.value=await api(`/reports?from=${from.value}&to=${to.value}`)}catch(e:any){error.value=e.message}}
function preset(days:number){const d=new Date();d.setDate(d.getDate()-days+1);from.value=day(d);to.value=day(new Date());load()}
function csv(){if(!data.value)return;const text='Orden,Cliente,Venta,Costo directo,Cobrado\n'+data.value.orders.map((o:Row)=>[o.id,'"'+String(o.customer_name).replaceAll('"','""')+'"',o.total,o.direct_cost,o.paid].join(',')).join('\n');const url=URL.createObjectURL(new Blob(['\uFEFF'+text],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='reporte-taller.csv';a.click();URL.revokeObjectURL(url)}
onMounted(load)
</script>
<template><div class="page-heading"><div><p class="eyebrow">DECISIONES CON INFORMACIÓN</p><h1>Reportes del taller</h1><p class="muted">Servicios entregados, cobros y carga de trabajo.</p></div><button class="btn secondary" @click="csv"><Icon name="chart"/>Exportar CSV</button></div><section class="panel report-filter"><form class="button-row" @submit.prevent="load"><label>Desde<input v-model="from" type="date" required></label><label>Hasta<input v-model="to" type="date" required :min="from"></label><button class="btn primary">Consultar</button></form><div class="button-row"><button v-for="[days,label] in [[1,'Hoy'],[7,'7 días'],[15,'15 días'],[30,'30 días']]" class="btn secondary small-btn" @click="preset(Number(days))">{{label}}</button></div></section><p v-if="error" class="error">{{error}}</p><template v-if="data"><section class="stats-grid"><article v-for="[key,label] in [['revenue','Servicios entregados'],['cost','Costos directos'],['margin','Margen bruto'],['payments','Cobros netos del período']]" class="stat-card"><div class="stat-label">{{label}}</div><strong class="money-stat">{{money(data[key])}}</strong><small>MXN · Período seleccionado</small></article></section><section class="panel"><div class="panel-heading"><h2>Servicios entregados</h2><span class="count-pill">{{data.orders.length}}</span></div><div class="table-wrap"><table><thead><tr><th>Orden</th><th>Cliente</th><th>Venta</th><th>Costo directo</th><th>Margen</th></tr></thead><tbody><tr v-for="o in data.orders"><td><RouterLink class="text-link" :to="'/orders/'+o.id">#{{o.id}}</RouterLink></td><td>{{o.customer_name}}</td><td>{{money(o.total)}}</td><td>{{money(o.direct_cost)}}</td><td>{{money(o.total-o.direct_cost)}}</td></tr></tbody></table><div v-if="!data.orders.length" class="empty"><Icon name="chart" :size="36"/><h3>Aún no hay servicios entregados en este período</h3><p>Los cobros se registran por fecha de pago, aunque la orden siga abierta.</p></div></div></section><section class="panel workload"><div class="panel-heading"><h2>Carga actual del equipo</h2></div><div v-for="e in data.workload" class="payment-row"><span class="avatar pale">{{e.full_name.slice(0,2).toUpperCase()}}</span><strong class="grow">{{e.full_name}}</strong><span>{{e.active_orders}} órdenes activas</span></div></section></template></template>
